In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
poverty_data=pd.read_csv('/content/drive/MyDrive/CP project/Project/Raw Datasets/poverty data.csv',skiprows=3,sep=';')
poverty_data.head()

,State FIPS Code,County FIPS Code,Postal Code,Name,"Poverty Estimate, All Ages",90% CI Lower Bound,90% CI Upper Bound,"Poverty Percent, All Ages",90% CI Lower Bound.1,90% CI Upper Bound.1,...,90% CI Upper Bound.5,Median Household Income,90% CI Lower Bound.6,90% CI Upper Bound.6,"Poverty Estimate, Age 0-4",90% CI Lower Bound.7,90% CI Upper Bound.7,"Poverty Percent, Age 0-4",90% CI Lower Bound.8,90% CI Upper Bound.8
0,0,0,US,United States,38.371.394,38.309.115,38.433.673,"11,9","11,9","11,9",...,"14,9",67.340,67.251,67.429,3.146.325,3.133.736,3.158.914,"16,8","16,7","16,9"
1,1,0,AL,Alabama,714.568,695.249,733.887,"14,9","14,5","15,3",...,"20,7",53.958,53.013,54.903,66.169,61.541,70.797,"23,3","21,7","24,9"
2,1,1,AL,Autauga County,6.242,4.930,7.554,"11,2","8,8","13,6",...,"19,3",67.565,59.132,75.998,.,.,.,.,.,.
3,1,3,AL,Baldwin County,20.189,15.535,24.843,"8,9","6,8","11,0",...,"16,1",71.135,66.540,75.730,.,.,.,.,.,.
4,1,5,AL,Barbour County,5.548,4.210,6.886,"25,5","19,3","31,7",...,"47,2",38.866,33.510,44.222,.,.,.,.,.,.

In [ ]:
poverty_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3195 entries, 0 to 3194
Data columns (total 31 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   State FIPS Code                         3195 non-null   int64
 1   County FIPS Code                        3195 non-null   int64
 2   Postal Code                             3195 non-null   object
 3   Name                                    3195 non-null   object
 4   Poverty Estimate, All Ages              3195 non-null   object
 5   90% CI Lower Bound                      3195 non-null   object
 6   90% CI Upper Bound                      3195 non-null   object
 7   Poverty Percent, All Ages               3195 non-null   object
 8   90% CI Lower Bound.1                    3195 non-null   object
 9   90% CI Upper Bound.1                    3195 non-null   object
 10  Poverty Estimate, Age 0-17              3195 non-null   object
 11  90% CI Lower Bound.2                    3195 non-null   object
 12  90% CI Upper Bound.2                    3195 non-null   object
 13  Poverty Percent, Age 0-17               3195 non-null   object
 14  90% CI Lower Bound.3                    3195 non-null   object
 15  90% CI Upper Bound.3                    3195 non-null   object
 16  Poverty Estimate, Age 5-17 in Families  3195 non-null   object
 17  90% CI Lower Bound.4                    3195 non-null   object
 18  90% CI Upper Bound.4                    3195 non-null   object
 19  Poverty Percent, Age 5-17 in Families   3195 non-null   object
 20  90% CI Lower Bound.5                    3195 non-null   object
 21  90% CI Upper Bound.5                    3195 non-null   object
 22  Median Household Income                 3195 non-null   object
 23  90% CI Lower Bound.6                    3195 non-null   object
 24  90% CI Upper Bound.6                    3195 non-null   object
 25  Poverty Estimate, Age 0-4               3195 non-null   object
 26  90% CI Lower Bound.7                    3195 non-null   object
 27  90% CI Upper Bound.7                    3195 non-null   object
 28  Poverty Percent, Age 0-4                3195 non-null   object
 29  90% CI Lower Bound.8                    3195 non-null   object
 30  90% CI Upper Bound.8                    3195 non-null   object
dtypes: int64(2), object(29)
memory usage: 773.9+ KB

In [ ]:
poverty_data.replace('.', np.nan, inplace=True)

poverty_data.isnull().sum()

State FIPS Code                              0
County FIPS Code                             0
Postal Code                                  0
Name                                         0
Poverty Estimate, All Ages                   1
90% CI Lower Bound                           1
90% CI Upper Bound                           1
Poverty Percent, All Ages                    1
90% CI Lower Bound.1                         1
90% CI Upper Bound.1                         1
Poverty Estimate, Age 0-17                   1
90% CI Lower Bound.2                         1
90% CI Upper Bound.2                         1
Poverty Percent, Age 0-17                    1
90% CI Lower Bound.3                         1
90% CI Upper Bound.3                         1
Poverty Estimate, Age 5-17 in Families       1
90% CI Lower Bound.4                         1
90% CI Upper Bound.4                         1
Poverty Percent, Age 5-17 in Families        1
90% CI Lower Bound.5                         1
90% CI Upper Bound.5                         1
Median Household Income                      1
90% CI Lower Bound.6                         1
90% CI Upper Bound.6                         1
Poverty Estimate, Age 0-4                 3143
90% CI Lower Bound.7                      3143
90% CI Upper Bound.7                      3143
Poverty Percent, Age 0-4                  3143
90% CI Lower Bound.8                      3143
90% CI Upper Bound.8                      3143
dtype: int64

In [ ]:
# Let's check if FIPS code can be used as County identifiers
# Conta quante volte ogni 'County FIPS Code' appare
fips_counts = poverty_data['County FIPS Code'].value_counts()
print(fips_counts)

County FIPS Code
0      52
3      49
5      49
1      49
9      48
       ..
367     1
369     1
371     1
373     1
78      1
Name: count, Length: 326, dtype: int64

In [ ]:
# This because it's combination between the FIPS and the state to be unique
poverty_data[poverty_data.duplicated(subset=['Postal Code', 'County FIPS Code'], keep=False)]

Empty DataFrame
Columns: [State FIPS Code, County FIPS Code, Postal Code, Name, Poverty Estimate, All Ages, 90% CI Lower Bound, 90% CI Upper Bound, Poverty Percent, All Ages, 90% CI Lower Bound.1, 90% CI Upper Bound.1, Poverty Estimate, Age 0-17, 90% CI Lower Bound.2, 90% CI Upper Bound.2, Poverty Percent, Age 0-17, 90% CI Lower Bound.3, 90% CI Upper Bound.3, Poverty Estimate, Age 5-17 in Families, 90% CI Lower Bound.4, 90% CI Upper Bound.4, Poverty Percent, Age 5-17 in Families, 90% CI Lower Bound.5, 90% CI Upper Bound.5, Median Household Income, 90% CI Lower Bound.6, 90% CI Upper Bound.6, Poverty Estimate, Age 0-4, 90% CI Lower Bound.7, 90% CI Upper Bound.7, Poverty Percent, Age 0-4, 90% CI Lower Bound.8, 90% CI Upper Bound.8]
Index: []

[0 rows x 31 columns]

In [ ]:
poverty_data['Postal Code'].unique()

array(['US', 'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL',
       'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD',
       'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM',
       'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN',
       'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'], dtype=object)

In [ ]:
# the the last columns contain too many Nan values to be analyzed
poverty_data.drop(['Poverty Estimate, Age 0-4','90% CI Lower Bound.7','90% CI Upper Bound.7',
                   'Poverty Percent, Age 0-4','90% CI Lower Bound.8','90% CI Upper Bound.8'
                  ],inplace=True,axis=1)


# Let's now select only the interested columns
poverty_data=poverty_data[['County FIPS Code','Postal Code','Name','Poverty Estimate, All Ages',
                         'Poverty Percent, All Ages','Median Household Income',
                          'Poverty Estimate, Age 0-17','Poverty Percent, Age 0-17'
                         ]]

poverty_data.head()

,County FIPS Code,Postal Code,Name,"Poverty Estimate, All Ages","Poverty Percent, All Ages",Median Household Income,"Poverty Estimate, Age 0-17","Poverty Percent, Age 0-17"
0,0,US,United States,38.371.394,"11,9",67.340,11.204.423,"15,7"
1,0,AL,Alabama,714.568,"14,9",53.958,222.934,"20,9"
2,1,AL,Autauga County,6.242,"11,2",67.565,1.912,"14,9"
3,3,AL,Baldwin County,20.189,"8,9",71.135,5.907,"12,4"
4,5,AL,Barbour County,5.548,"25,5",38.866,1.857,"37,5"

In [ ]:
poverty_data['Poverty Estimate, All Ages'] = poverty_data['Poverty Estimate, All Ages'].str.replace(',', '').str.replace('.', '').astype(float)
poverty_data['Poverty Percent, All Ages'] = poverty_data['Poverty Percent, All Ages'].str.replace(',', '.').astype(float)
poverty_data['Median Household Income'] = poverty_data['Median Household Income'].str.replace(',', '').astype(float)
poverty_data['Poverty Estimate, Age 0-17'] = poverty_data['Poverty Estimate, Age 0-17'].str.replace(',', '').str.replace('.', '').astype(float)
poverty_data['Poverty Percent, Age 0-17'] = poverty_data['Poverty Percent, Age 0-17'].str.replace(',', '.').astype(float)

poverty_data.rename(columns={
    'Postal Code':'State',
    'Name':'County',
    'County FIPS Code':'FIPS'
},inplace=True)


poverty_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3195 entries, 0 to 3194
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   FIPS                        3195 non-null   int64
 1   State                       3195 non-null   object
 2   County                      3195 non-null   object
 3   Poverty Estimate, All Ages  3194 non-null   float64
 4   Poverty Percent, All Ages   3194 non-null   float64
 5   Median Household Income     3194 non-null   float64
 6   Poverty Estimate, Age 0-17  3194 non-null   float64
 7   Poverty Percent, Age 0-17   3194 non-null   float64
dtypes: float64(5), int64(1), object(2)
memory usage: 199.8+ KB

<ipython-input-20-7a375a4ee70e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_data['Poverty Estimate, All Ages'] = poverty_data['Poverty Estimate, All Ages'].str.replace(',', '').str.replace('.', '').astype(float)
<ipython-input-20-7a375a4ee70e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_data['Poverty Percent, All Ages'] = poverty_data['Poverty Percent, All Ages'].str.replace(',', '.').astype(float)
<ipython-input-20-7a375a4ee70e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_data['Median Household Income'] = poverty_data['Median Household Income'].str.replace(',', '').astype(float)
<ipython-input-20-7a375a4ee70e>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_data['Poverty Estimate, Age 0-17'] = poverty_data['Poverty Estimate, Age 0-17'].str.replace(',', '').str.replace('.', '').astype(float)
<ipython-input-20-7a375a4ee70e>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_data['Poverty Percent, Age 0-17'] = poverty_data['Poverty Percent, Age 0-17'].str.replace(',', '.').astype(float)
<ipython-input-20-7a375a4ee70e>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_data.rename(columns={

In [ ]:
# Just to avoid repetitions and to make the dataset more consistent with the other datasets
# let's remove the word 'County'
poverty_data['County'] = poverty_data['County'].str.replace(' County', '', regex=False)

<ipython-input-21-e8594878ea84>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty_data['County'] = poverty_data['County'].str.replace(' County', '', regex=False)

In [ ]:
poverty_data.to_csv('/content/drive/MyDrive/CP project/Project/Cleaned Datasets/2020 poverty data.csv',index=False)

In [ ]:
poverty_state_data = poverty_data.pivot_table(
    index="State",
    values=[
        "Poverty Estimate, All Ages", "Poverty Percent, All Ages",
        "Median Household Income", "Poverty Estimate, Age 0-17",
        "Poverty Percent, Age 0-17"
    ],
    aggfunc={
        "Poverty Estimate, All Ages": "sum",
        "Poverty Estimate, Age 0-17": "sum",
        "Poverty Percent, All Ages": "mean",
        "Poverty Percent, Age 0-17": "mean",
        "Median Household Income": "mean"
    }
)
poverty_state_data

,Median Household Income,"Poverty Estimate, Age 0-17","Poverty Estimate, All Ages","Poverty Percent, Age 0-17","Poverty Percent, All Ages"
State,,,,,
AK,72.274581,42918.0,137428.0,16.161290,12.200000
AL,47.945147,445866.0,1429138.0,25.208824,17.557353
AR,45.769132,285709.0,897332.0,25.119737,17.834211
AZ,54.338250,567333.0,1865108.0,21.662500,16.068750
CA,74.261186,2520287.0,8838334.0,15.366102,12.262712
CO,65.739985,259673.0,1022695.0,14.875385,11.435385
CT,80.536000,167870.0,666870.0,10.422222,8.977778
DC,91.957000,56840.0,203918.0,22.300000,15.000000
DE,69.461750,60760.0,208800.0,15.700000,11.250000
FL,56.670882,1429688.0,5285285.0,21.172059,14.752941
GA,52.546775,959140.0,2930653.0,25.785625,18.049375
HI,81.611000,59363.0,242364.0,11.260000,9.700000
IA,61.359650,170376.0,627508.0,12.690000,9.974000
ID,57.917444,102386.0,362393.0,15.002222,11.453333
IL,60.386136,755356.0,2702310.0,15.227184,11.571845
IN,60.639129,457664.0,1520337.0,14.435484,10.950538
KS,57.035726,176984.0,601861.0,14.868868,11.274528
KY,48.794529,379390.0,1294313.0,24.292562,17.968595
LA,48.580692,516413.0,1604076.0,27.960000,20.170769
MA,82.195600,286398.0,1257796.0,11.100000,9.300000
MD,82.023600,293260.0,1067122.0,13.436000,10.196000
ME,56.682706,61224.0,279229.0,14.652941,11.452941
MI,56.025917,699692.0,2465895.0,17.598810,12.457143
MN,65.994784,242032.0,916603.0,10.640909,8.702273
MO,51.426621,416820.0,1450233.0,20.274138,14.677586
MS,43.909181,351995.0,1073070.0,29.926506,21.426506
MT,53.371561,65898.0,261422.0,18.303509,14.222807
NC,53.330069,809456.0,2659373.0,22.134653,15.261386
ND,60.681537,38940.0,151562.0,14.079630,11.053704
NE,57.668521,94129.0,345241.0,13.535106,10.335106
NH,74.482273,41452.0,184808.0,10.036364,7.990909
NJ,85.510455,477889.0,1636779.0,12.140909,9.227273
NM,48.409000,199152.0,692909.0,25.547059,18.497059
NV,64.499389,228746.0,773634.0,15.016667,11.827778
NY,65.339476,1306599.0,4802283.0,16.252381,11.919048
OH,59.549079,834663.0,2856442.0,16.014607,11.940449
OK,50.757756,346808.0,1104335.0,20.760256,15.637179
OR,60.333784,204905.0,915883.0,15.527027,12.362162
PA,59.818750,735608.0,2691953.0,15.257353,11.252941
RI,80.636333,57904.0,216612.0,12.033333,9.333333
SC,51.103021,411552.0,1406007.0,23.965957,16.810638
SD,54.139597,59510.0,199809.0,18.994030,15.049254
TN,51.882260,544677.0,1822195.0,20.913542,15.179167
TX,57.325592,2747293.0,7725431.0,20.969020,14.532549
US,67.340000,11204423.0,38371394.0,15.700000,11.900000
UT,68.475167,137801.0,469333.0,11.480000,9.080000
VA,64.895694,447235.0,1538958.0,16.829104,12.217164
VT,64.014133,22121.0,112561.0,11.233333,9.660000
WA,65.179150,358135.0,1429308.0,15.212500,11.907500
WI,62.543082,305192.0,1142093.0,12.501370,9.545205
WV,47.571232,140802.0,548351.0,22.057143,16.741071
WY,65.546167,26926.0,104838.0,10.966667,9.520833

In [ ]:
poverty_data[poverty_data['State']=='AK']

,FIPS,State,County,"Poverty Estimate, All Ages","Poverty Percent, All Ages",Median Household Income,"Poverty Estimate, Age 0-17","Poverty Percent, Age 0-17"
69,0,AK,Alaska,68714.0,9.6,79.961,21459.0,12.3
70,13,AK,Aleutians East Borough,514.0,15.1,79.128,31.0,13.2
71,16,AK,Aleutians West Census Area,443.0,8.1,92.216,40.0,6.0
72,20,AK,Anchorage Borough,23200.0,8.3,84.577,6026.0,9.0
73,50,AK,Bethel Census Area,4567.0,25.3,52.214,2347.0,36.8
74,60,AK,Bristol Bay Borough,82.0,10.7,87.032,18.0,11.8
75,63,AK,Chugach Census Area,441.0,7.0,84.063,99.0,7.2
76,66,AK,Copper River Census Area,368.0,12.7,61.215,120.0,16.6
77,68,AK,Denali Borough,127.0,6.4,80.192,25.0,7.2
78,70,AK,Dillingham Census Area,894.0,18.7,72.334,394.0,26.5
79,90,AK,Fairbanks North Star Borough,6565.0,7.2,76.650,1751.0,7.9
80,100,AK,Haines Borough,251.0,9.6,105.044,83.0,18.4
81,105,AK,Hoonah-Angoon Census Area,271.0,12.7,55.593,89.0,23.2
82,110,AK,Juneau Borough,2510.0,8.1,89.204,768.0,11.9
83,122,AK,Kenai Peninsula Borough,6171.0,10.6,68.448,1898.0,14.7
84,130,AK,Ketchikan Gateway Borough,1127.0,8.3,76.780,273.0,9.8
85,150,AK,Kodiak Island Borough,957.0,7.5,72.028,244.0,8.1
86,158,AK,Kusilvak Census Area,2305.0,27.9,37.566,1449.0,42.5
87,164,AK,Lake and Peninsula Borough,261.0,17.6,54.386,97.0,23.0
88,170,AK,Matanuska-Susitna Borough,9365.0,8.7,89.502,2677.0,9.5
89,180,AK,Nome Census Area,1825.0,18.8,64.309,765.0,23.1
90,185,AK,North Slope Borough,1025.0,11.1,94.759,353.0,14.0
91,188,AK,Northwest Arctic Borough,1397.0,18.5,65.194,689.0,25.4
92,195,AK,Petersburg Borough,242.0,7.4,66.096,64.0,9.4
93,198,AK,Prince of Wales-Hyder Census Area,975.0,15.9,53.638,274.0,20.9
94,220,AK,Sitka Borough,609.0,7.4,79.363,132.0,7.9
95,230,AK,Skagway Municipality,45.0,3.8,78.421,9.0,5.0
96,240,AK,Southeast Fairbanks Census Area,805.0,11.7,64.544,267.0,15.2
97,275,AK,Wrangell City and Borough,264.0,10.6,64.643,61.0,13.1
98,282,AK,Yakutat Borough,79.0,12.4,68.352,31.0,23.8
99,290,AK,Yukon-Koyukuk Census Area,1029.0,20.5,43.060,385.0,27.6

In [ ]:
poverty_state_data.to_csv('/content/drive/MyDrive/CP project/Project/Cleaned Datasets/2020 poverty data per state.csv',index=True)